security:
  jwt:
    client-id: moko
    client-secret: bike
    grant-type: password
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid
  signing-key: MaYzkSjmkzPC57L
  encoding-strength: 256
  security-realm: Spring Boot JWT Mokobike Realm
  oauth2:
    resource:
      filter-order: 3

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spittrdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxx@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


logging:
  level:
    root: ERROR
    com.mokobike: TRACE
    org.springframework: WARN
    org.springframework.jdbc: TRACE

  file: /D:/KODZENIE/mokobike/target/application.log

